gitlab-ci: bump ruby to 2.6
It now fails with:

```
$ gem install apiaryio
....
35ERROR:  Error installing apiaryio:
36	The last version of public_suffix (>= 2.0.2, < 6.0) to support your Ruby & RubyGems was 4.0.7. Try installing it with `gem install public_suffix -v 4.0.7` and then running the current command again
	public_suffix requires Ruby version >= 2.6. The current ruby version is 2.4.10.364.
38Successfully installed json-2.6.2
```

Signed-off-by: Miroslav Vadkerti <mvadkert@redhat.com>